In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.neighbors import KNeighborsClassifier


In [2]:
titanic = sns.load_dataset('titanic')

In [4]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [6]:
titanic = titanic[["survived","pclass","sex","age"]]


In [10]:
titanic.dropna(axis=0,inplace=True)

/var/folders/jl/83qf498555s5dk6k_w6b1j_m0000gn/T/ipykernel_25640/1977443898.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic.dropna(axis=0,inplace=True)


In [12]:
titanic['sex'].replace(['male','female'],[0,1],inplace=True)

/var/folders/jl/83qf498555s5dk6k_w6b1j_m0000gn/T/ipykernel_25640/2933321421.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['sex'].replace(['male','female'],[0,1],inplace=True)


In [13]:
titanic


survived  pclass  sex   age
0           0       3    0  22.0
1           1       1    1  38.0
2           1       3    1  26.0
3           1       1    1  35.0
4           0       3    0  35.0
..        ...     ...  ...   ...
885         0       3    1  39.0
886         0       2    0  27.0
887         1       1    1  19.0
889         1       1    0  26.0
890         0       3    0  32.0

[714 rows x 4 columns]

In [16]:
model = KNeighborsClassifier()

In [14]:
y = titanic['survived']

In [18]:
X = titanic.drop('survived',axis=1)

In [19]:
model.fit(X,y)

KNeighborsClassifier()

In [20]:
model.score(X,y)

0.8417366946778712

In [29]:
def has_survived(model,pclass=3,sex=0,age=46):
    x = np.array([pclass,sex,age]).reshape(1,3)
    print(np.array([pclass,sex,age]))
    print(x)
    return model.predict(x)

In [36]:
has_survived(model,pclass=1,sex=0,age=20)

[ 1  0 20]
[[ 1  0 20]]


/Users/fgaurat/local_dev/formations/pythonperf/tp15/.venv/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])